service: instaBOT

plugins:
  - serverless-bundle
  - serverless-webpack
  - serverless-prune-plugin
  - serverless-iam-roles-per-function
  - serverless-dotenv-plugin

custom: ${file(sls/custom/index.yml)}

package:
  patterns:
    - '!node_modules/**'

provider:
  architecture: arm64
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  memorySize: ${self:custom.memorySize.${self:custom.stage}}
  versionFunctions: false
  environment:
    a: '2'

functions:
  - ${file(sls/functions/instaScraper.yml)}
#resources: ${file(sls/resources/index.yml)}
